In [5]:
import numpy as np
from scipy.stats import bernoulli, binom

In [2]:
print("----- Bernoulli Distribution -----")

----- Bernoulli Distribution -----


In [3]:
p = 0.7

In [6]:
bernoulli_samples = bernoulli.rvs(p, size=10)
print("Probability of Passing:", p)
print("Student Outcomes (1=Pass, 0=Fail):")
print(bernoulli_samples)

Probability of Passing: 0.7
Student Outcomes (1=Pass, 0=Fail):
[1 1 1 1 1 1 1 0 0 1]


In [7]:
print("\nProbability of Pass:")
print(bernoulli.pmf(1, p))
print("Probability of Fail:")
print(bernoulli.pmf(0, p))


Probability of Pass:
0.7
Probability of Fail:
0.30000000000000004


In [8]:
print("\n\n----- Binomial Distribution -----")



----- Binomial Distribution -----


In [9]:
n = 10

In [10]:
p = 0.7

In [11]:
k = 8
binomial_probability = binom.pmf(k, n, p)
print("Number of Students:", n)
print("Probability of Passing:", p)
print(f"\nProbability that exactly {k} students pass:")
print(binomial_probability)

Number of Students: 10
Probability of Passing: 0.7

Probability that exactly 8 students pass:
0.23347444050000013


In [12]:
random_binomial = binom.rvs(n, p, size=5)
print("\nRandom Binomial Outcomes:")
print(random_binomial)


Random Binomial Outcomes:
[ 8  8  8 10  5]


In [13]:
import numpy as np
from scipy import stats
from statsmodels.stats.weightstats import ztest

In [14]:
print("----- Z-Test -----")

----- Z-Test -----


In [15]:
sample_marks = np.array([78, 82, 85, 88, 90, 76, 95, 89, 84, 91])

In [16]:
population_mean = 80

In [17]:
z_stat, p_value = ztest(sample_marks, value=population_mean)
print("Sample Marks:")
print(sample_marks)
print("\nPopulation Mean:", population_mean)
print("\nZ-Statistic:", z_stat)
print("P-Value:", p_value)

Sample Marks:
[78 82 85 88 90 76 95 89 84 91]

Population Mean: 80

Z-Statistic: 3.0778387488959273
P-Value: 0.0020850770735042832


In [18]:
alpha = 0.05
if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")


Result: Reject Null Hypothesis


In [19]:
print("\n\n----- Independent t-Test -----")
# Marks of two different classes
class_A = np.array([78, 82, 85, 88, 90])
class_B = np.array([72, 75, 70, 68, 74])



----- Independent t-Test -----


In [20]:
t_stat, p_value = stats.ttest_ind(class_A, class_B)
print("Class A Marks:")
print(class_A)
print("\nClass B Marks:")
print(class_B)
print("\nt-Statistic:", t_stat)
print("P-Value:", p_value)


Class A Marks:
[78 82 85 88 90]

Class B Marks:
[72 75 70 68 74]

t-Statistic: 5.140603704975992
P-Value: 0.000884475345807384


In [21]:
if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")



Result: Reject Null Hypothesis
